name: 'Add to Milestone'
description: 'Add PR to a milestone'
author: 'andrefcdias'
inputs:
  repo-token:
    required: true
    description: 'Github token'
  milestone:
    required: true
    description: 'Milestone name'

runs:
  using: 'node12'
  main: 'dist/index.js'
